[2023-03-31T15:16:34.675+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T10:15:52.367936+00:00 [queued]>
[2023-03-31T15:16:34.690+0500] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T10:15:52.367936+00:00 [queued]>
[2023-03-31T15:16:34.691+0500] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T15:16:34.691+0500] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T15:16:34.693+0500] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T15:16:34.717+0500] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): show_data> on 2023-03-31 10:15:52.367936+00:00
[2023-03-31T15:16:34.742+0500] {standard_task_runner.py:55} INFO - Started process 1402 to run task
[2023-03-31T15:16:34.756+0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_Scraping_Dag', 'show_data', 'manual__2023-03-31T10:15:52.367936+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/AirFlow_Task.py', '--cfg-path', '/tmp/tmp6vvl62g8']
[2023-03-31T15:16:34.758+0500] {standard_task_runner.py:83} INFO - Job 59: Subtask show_data
[2023-03-31T15:16:34.872+0500] {task_command.py:388} INFO - Running <TaskInstance: my_Scraping_Dag.show_data manual__2023-03-31T10:15:52.367936+00:00 [running]> on host Jamshaid-PC.localdomain
[2023-03-31T15:16:34.954+0500] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jamshaid.afzal@tmcltd.com
AIRFLOW_CTX_DAG_OWNER=jamshaid
AIRFLOW_CTX_DAG_ID=my_Scraping_Dag
AIRFLOW_CTX_TASK_ID=show_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T10:15:52.367936+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T10:15:52.367936+00:00
[2023-03-31T15:16:36.942+0500] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/client.py", line 150, in open
    properties = finditem(
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/utils.py", line 133, in finditem
    return next(item for item in seq if func(item))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/mnt/c/dags/AirFlow_Task.py", line 57, in show_data
    sh = gc.open('BathBombScraper').sheet1
  File "/home/jamshaid/.local/lib/python3.10/site-packages/gspread/client.py", line 160, in open
    raise SpreadsheetNotFound
gspread.exceptions.SpreadsheetNotFound
[2023-03-31T15:16:37.001+0500] {taskinstance.py:1321} INFO - Marking task as FAILED. dag_id=my_Scraping_Dag, task_id=show_data, execution_date=20230331T101552, start_date=20230331T101634, end_date=20230331T101636
[2023-03-31T15:16:37.022+0500] {standard_task_runner.py:100} ERROR - Failed to execute job 59 for task show_data (; 1402)
[2023-03-31T15:16:37.055+0500] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T15:16:37.110+0500] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
